name: Onu
version: 1.6
main: pw.palistine.onu.Onu
author: Patrone Development Team
commands:
  setrank:
  kick:
  ban:
  tempban:
  mute:
  tempmute:
  unban:
  unmute:
  history:
  eat:
  heal:
  ranks:
  blacklist:
  unblacklist:
  shutdown:
  report:
  ping:
  r:
  tpm:
  clearchat:
     aliases: [cc]
  discord:
  teamspeak:
      aliases: [ts]
  mutechat:
      aliases: [mc, mchat]
  staffchat:
      aliases: [sc]
  broadcast:
      aliases: [bc]
  freeze:
      aliases: [ss]
  msg:
      aliases: [w, m, message]



