Time: 120
Broadcasts:
  - '&8[&4Alert&8] &fJoin our discord &9https//disc.valorpvp.club'
  - '&8[&4Alert&8] &fWanna support the server buy a rank at &9shop.valorpvp.club'
  - '&8[&4Alert&8] &fWe are currently looking for staff apply at &9 valorpvp.club/apply'