name: Hermes
version: 1
main: me.kxda.hermes.Hermes
author: kxda, Palistine
commands:
  setrank:
  kick:
  ban:
  tempban:
  mute:
  tempmute:
  unban:
  unmute:
  history:
  eat:
    aliases: [feed]
  heal:
  ranks:
  blacklist:
    aliases: [leftbooblisted, bl, zacklacey]
  unblacklist:
    aliases: [unbl]
  shutdown:
  report:
  ping:
  r:
  tpm:
  clearchat:
     aliases: [cc]
  discord:
  teamspeak:
      aliases: [ts]
  mutechat:
      aliases: [mc, mchat]
  adminchat:
    aliases: [ac]
  staffchat:
      aliases: [sc]
  broadcast:
      aliases: [bc]
  freeze:
      aliases: [ss]
  msg:
      aliases: [w, m, message]
  hermes:
      aliases: [core, kxdaisdaddy]
  rail:
  gms:
  gmc:
  gma:
  teleport:
      aliases: [tp]